channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - haversine
  - ipywidgets
  - jupyter
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - paramiko
  - pooch
  - psutil
  - pyproj>=2.6
  - pytz
  - rasterio
  - rasterstats
  - requests
  - scipy
  - geopy
  - searvey
  - shapely
  - plotly
  - utm
  - xarray
  - pyyaml
  - appdirs
  - nco
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - myst-parser
  - cartopy
